### PR TITLE
[WIP] Generate doc from source

### PR DESCRIPTION
**Pull request by wsdjeg**
This PR is going to move all help doc into source code, and generate the help file automatically. also we should fix lint for vimscript.

before this PR is merged, we use `vim-javacomplete2` as default tag to avoid conflicts.

### CODE REVIEW

**Comment by artur-shaik** [comment]
Hello, nice work. Is it still WIP?

**Comment by wsdjeg** [comment]
yeah, It is WIP now.

**Comment by artur-shaik** [comment]
Is it ready to be merged?

**Comment by wsdjeg** [comment]
no, will be finished next week.

**Comment by wsdjeg** [comment]
@artur-shaik This PR is done.

**Comment by artur-shaik** [comment]
Thanks

**Pull request merged**
