### PR TITLE
fix miss src when Definitions g:JavaComplete_SourcesPath

### PR DESCRIPTION
**Pull request by wsdjeg**
I have reset my repo ,then the gitdiff seems clearer

### CODE REVIEW

**Comment by mattn** [comment]
please don't repeat same code. if you want to get g:JavaComplete_SourcePath in non-configured cases or configured cases, you can do it like below.

```
let g:JavaComplete_SourcePath = get(g:, 'JavaComplete_SourcePath', '')
```

**Comment by wsdjeg** [comment]
thank you for tell me ,i will have a try

**Comment by wsdjeg** [comment]
sorry i can not fix it, both non-configured cases or configured cases needs get all the "src/" in this project,
maybe we can split these code into an function?

**Comment by mattn** [comment]
Sorry, I'm not talking you should do only thing that I said. You need to do more something to avoid to write same code to implement. :)

**Comment by wsdjeg** [comment]
i have fixed it

**Comment by artur-shaik** [comment]
Let me write, how I understand you:
So, you want append sources paths even if Javacomplete_SourcesPath already set? If so, why not just remove `exists` condition and use `get` for variable initialization?

**Comment by wsdjeg** [comment]
i have removed the exists condition

**Comment by artur-shaik** [comment]
Yeah, but you also use temporary variable. Do we really need it?

**Comment by mattn** [comment]
@wsdjeg patch should be like below.
```diff
diff --git a/autoload/javacomplete.vim b/autoload/javacomplete.vim
index 4084213..9139390 100644
--- a/autoload/javacomplete.vim
+++ b/autoload/javacomplete.vim
@@ -233,19 +233,17 @@ let g:JavaComplete_JavaParserJar = fnamemodify(g:JavaComplete_Home. "/libs/javap
 
 call javacomplete#logger#Log("JavaComplete_Home: ". g:JavaComplete_Home)
 
-if !exists("g:JavaComplete_SourcesPath")
-  let g:JavaComplete_SourcesPath = ''
-  let sources = s:GlobPathList(getcwd(), 'src', 0)
-  for i in ['*/', '*/*/', '*/*/*/']
-    call extend(sources, s:GlobPathList(getcwd(), i. '/src', 0))
-  endfor
-  for src in sources
-    if match(src, '.*build.*') < 0
-      let g:JavaComplete_SourcesPath = g:JavaComplete_SourcesPath. src. g:PATH_SEP
-    endif
-  endfor
-  call javacomplete#logger#Log("Default sources: ". g:JavaComplete_SourcesPath)
-endif
+let g:JavaComplete_SourcesPath = get(g:, 'JavaComplete_SourcesPath', '')
+let sources = s:GlobPathList(getcwd(), 'src', 0)
+for i in ['*/', '*/*/', '*/*/*/']
+  call extend(sources, s:GlobPathList(getcwd(), i. '/src', 0))
+endfor
+for src in sources
+  if match(src, '.*build.*') < 0
+    let g:JavaComplete_SourcesPath = g:JavaComplete_SourcesPath. src. g:PATH_SEP
+  endif
+endfor
+call javacomplete#logger#Log("Default sources: ". g:JavaComplete_SourcesPath)
 
 if !exists('g:JavaComplete_MavenRepositoryDisable') || !g:JavaComplete_MavenRepositoryDisable
   if exists('g:JavaComplete_LibsPath')
```

**Comment by wsdjeg** [comment]
let g:JavaComplete_SourcesPath = g:JavaComplete_SourcesPath. g:PATH_SEP .src
may be it will be better
if someone add this into vimrc
```vim
let g:JavaComplete_SourcesPath = "/path/to/src"
```

**Comment by artur-shaik** [comment]
@wsdjeg Please, modify request as @mattn and you suggested.

**Comment by wsdjeg** [comment]
ok i will do it

**Comment by mattn** [comment]
@artur-shaik BTW, variable `sources` is global variable. should rename to `s:sources` and `unlet s:sources` at the end of the part. I will make new pull-request after merging this in tomorrow maybe.

**Comment by wsdjeg** [comment]
hi @mattn  i just have add this

**Comment by mattn** [comment]
LGTM

**Pull request merged**
