### PR TITLE
Updating javaparser-core and json libs

### PR DESCRIPTION
**Pull request by adelarsq**
Update for the libs:
* com.github.javaparser javaparser-core 2.3.0
* org.json json 20151123

libs/javaparser.jar file is the same javaparser-core-2.3.0.jar from the maven repository.

### CODE REVIEW

**Comment by adelarsq** [comment]
@artur-shaik cancel this pull request?

**Comment by wsdjeg** [comment]
maybe need more test,do you know the diff between these version,will it break the completion

**Comment by artur-shaik** [comment]
Yes, we need to check difference and if is there any reason for update.

**Comment by adelarsq** [comment]
Just an update for the last version, because I didn't notice any improvement or breaks. Originally I was trying to see some speed improvement, but none occurred.

**Comment by adelarsq** [comment]
I will close this issue for now and wait for some improvement on the used libraries.

**Pull request closed without merging**
