### PR TITLE
Build CLASSPATH from maven

### PR DESCRIPTION
**Pull request by mattn**
make CLASSPATH from maven, and cache it.

### CODE REVIEW

**Comment by mattn** [comment]
Ah, sorry. it use webapi#http#encodeURIComponent. I'll remove dependency.

**Comment by artur-shaik** [comment]
Looks nice, thank you. Will play with it a little bit.

**Comment by mattn** [comment]
I'm thinking if you allow this, CLASSPATH which is contained `~/.m2` and athers are needless. how do you think?

**Comment by brcolow** [comment]
:+1:

**Comment by artur-shaik** [comment]
Yeah, of course, this approach is much better.

**Pull request merged**
