### PR TITLE
Update the README.md

### PR DESCRIPTION
**Pull request by wsdjeg**
add options info
* g:JavaComplete_ImportDefault
* g:JavaComplete_BaseDir

### CODE REVIEW

**Comment by wsdjeg** [comment]
I am really not good at english,maybe you can make it better.

**Comment by wsdjeg** [comment]
I think I should create new branch for PR

**Comment by artur-shaik** [comment]
I just merged it.

**Comment by wsdjeg** [comment]
thanks

**Comment by wsdjeg** [comment]
Are you try to use neovim ?

**Comment by artur-shaik** [comment]
Yes.

**Comment by wsdjeg** [comment]
if so ,maybe you can have a try with deoplete.vim + neosnippet.vim,

**Comment by artur-shaik** [comment]
I think later, when will have some more time.

On 01-11 (09:17), Wang Shidong wrote:
>    if so ,maybe you can have a try with deoplete.vim + neosnippet.vim,
> 
>    —
>    Reply to this email directly or [1]view it on GitHub.
> 
>    Reverse link: [2]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/artur-shaik/vim-javacomplete2/pull/178#issuecomment-170623214
>    2. https://github.com/artur-shaik/vim-javacomplete2/pull/178#issuecomment-170623214

-- 
Best regards,
Artur Shaikhullin

**Comment by wsdjeg** [comment]
I know,but now deoplete still haven't implemented all func of neocomplete

**Pull request closed without merging**
