### PR TITLE
fix https://github.com/artur-shaik/vim-javacomplete2/issues/136

### PR DESCRIPTION
**Pull request by wsdjeg**
i have fix it,please merge

### CODE REVIEW

**Comment by artur-shaik** [comment]
I think it would be better if you add your `gradlew` execution file in runtime path. Or link it to `bin` directory. Or may be we can add global variable for `gradle` execution file.

**Comment by wsdjeg** [comment]
now most android project contains itself gradlew,here are some example,
https://github.com/gitskarios/GithubAndroidSdk
https://github.com/gitskarios/Gitskarios-core
so there is no need to add gradlew into PATH,
but if you have installed gradle,`gradle` will be auto add into PATH,but `gradlew` will not

**Comment by wsdjeg** [comment]
and most people do not install gralde,they just use `./graldew` to build the app

**Comment by wsdjeg** [comment]
or ./gradlew.bat in Windows

**Comment by artur-shaik** [comment]
I see now. @DonnieWest, can you participate? What do you think?
As I understood, at least we need modifications for windows.

**Comment by wsdjeg** [comment]
sorry for my pool english ,meybe @DonnieWest knows

**Comment by DonnieWest** [comment]
@artur-shaik this looks good here. With Gradle wrapper you're not supposed to have gradlew on your path.

With Windows, if gradlew is present then also gradle.bat will be. I probably need to change line 191 to

``` let gradle = '. \gradle.bat' ```

And that should fix my buggy code. I just wish I had a Windows machine to test it out on. 

@wsdjeg would you mind making that change on line 191?

**Comment by DonnieWest** [comment]
Actually, I lied. More is needed to fix Windows. This pull request looks awesome, I'll submit another later on for Windows support

**Comment by wsdjeg** [comment]
i really do not see anyone add gradlew to PTAH,it is just a script,add gradle to PATH is significant

**Comment by artur-shaik** [comment]
@wsdjeg, yeah, that's ok, thank you.
@DonnieWest thanks.

**Comment by wsdjeg** [comment]
do you mean this ?

**Pull request merged**
