### PR TITLE
Remove doc tags

### PR DESCRIPTION
**Pull request by perrin4869**
hi, I sent you a pull request adding these to `.gitignore`, but I wanna retract them. I think these should still not be committed into the repository, since every user should generate them if they desire to do so. Maybe add them to a global `.gitignore`, (`git config --global core.excludesfile ~/.gitignore_global`), so as to keep ignoring them in your own environment.

### CODE REVIEW

**Comment by wsdjeg** [comment]
use global `.gitignore` maybe is not good idea.because sometimes I need add ./tags into repo,but sometimes I do not want add it.

**Comment by perrin4869** [comment]
hm... out of curiosity, what kind of `./tags` do you want to commit into a repo?

**Comment by wsdjeg** [comment]
sorry,it is hard to answer this question.but it is really need to remove this from the project's gitignore?

**Comment by perrin4869** [comment]
Not critical of course, but these files are automatically generated by end-users optionally, so conceptually speaking it doesn't make sense to ignore them.
Maybe you could override in the global `.gitignore`, as follows?

```
tags
!~/path/to/my/project/tags
```

**Comment by wsdjeg** [comment]
@perrin4869 I got it thanks

**Pull request merged**
