### PR TITLE
Redefine Gradle task and deduplicate classpath calls

### PR DESCRIPTION
**Pull request by DonnieWest**
1. Switch from << (leftShift) task definition that's been deprecated in Gradle to supported version
2. Define the classpath task for only the root project to remove duplicate calls for all sub projects

### CODE REVIEW

**Comment by DonnieWest** [comment]
@artur-shaik rebased this PR, pulled in the changes you made to the gradle functionality. I wasn't sure if deleting your branch was intentional or not, but, they work really well and I'd like to keep them if possible unless you have other plans

**Comment by artur-shaik** [comment]
Yeah, basically, the changes now in `develop` branch. Need to make some regularity on versioning, so before bump version, will push everything in `develop` branch.

**Comment by DonnieWest** [comment]
Gotcha - I'll rebase this off of develop tomorrow and resubmit then :-)

**Comment by DonnieWest** [comment]
Gotcha - thanks for pulling it in :-)

Edit: deleted my last comment since I misread you

**Pull request closed without merging**
