### PR TITLE
Support for Google style import ordering

### PR DESCRIPTION
**Pull request by not-napoleon**
The google style guide wants third party packages in between the project's packages and the standard library packages (see https://google.github.io/styleguide/javaguide.html#s3.3-import-statements).  This PR adds support for that by allowing a `*` character in the ImportOrder list, which will match any package not otherwise specified in the list.

This PR also makes sorting imports available as a <Plug> mapping in both normal and insert modes, as `<Plug>(JavaComplete-Imports-SortImports)`.  

Please don't feel obligated to incorporate this feature if it's not in line with your plan.  It's something I needed, and figured I should offer back just in case you wanted it.  If you need me to make modifications to this before merging, I'm open to that but will be traveling a lot in the next few weeks so may not be very responsive until mid August (2016).

Thank you!

### CODE REVIEW

**Comment by wsdjeg** [comment]
I got it, with `let g:JavaComplete_ImportOrder = ['com.google.', *, 'java.', 'javax.']` makes sort look like:
```java
package com.google;

import com.google.Test;

import net.vim.Test;
import org.vim.Test;

import java.util.Data;

public class Foo{}
```
but for different project, the first item in `g:JavaComplete_ImportOrder` is not same.

so I think it is better to keep g:JavaComplete_ImportOrder works same as before.

and, when sortting imports, auto detect the package statement. and put the package_name and '*' at the first and second position, BTW this func should not change value of g:JavaComplete_ImportOrder, that will make JC2 works well in other project.

**Comment by not-napoleon** [comment]
Ah, yeah, I use local-vimrc to manage multiple projects, so hadn't even thought about that issue.  I'm not sure about matching the package name though; consider:

```java
package com.google.aaa;

import com.google.bbb.Test;
import com.google.ccc.OtherTool;

import net.vim.Test;
import org.vim.Test;

import java.util.Data;

public class Foo{}
```

Would need a setting for how much of the path to match, which could default to first two elements.  If the user doesn't put the wildcard in the `g:JavaComplete_ImportOrder` list, how do we know to invoke this sort method?  New top level config var?

I don't mind building it this way, I just want to make sure I understand what you're looking for.  Thanks for the feedback!

**Comment by wsdjeg** [comment]
local-vimrc   is a good idea. I will merge your branch locally. and add something about auto detect package name of current java file.

this just will make user without local-vimrc feel better.

**Comment by wsdjeg** [comment]
@not-napoleon can you have a try with my new branch?

https://github.com/wsdjeg/vim-javacomplete2/tree/improve_sort

**Comment by artur-shaik** [comment]
@not-napoleon thanks for PR. I'll wait until you confirm @wsdjeg changes.

**Comment by not-napoleon** [comment]
@artur-shaik Sorry for the delay, I've been out of town.  I tested @wsdjeg changes this morning, and they seem fine to me.  Thanks for your help getting this merged, I look forward to running against the mainline again :)

**Comment by artur-shaik** [comment]
Thanks

**Pull request merged**
