### PR TITLE
Improve finding jar files.

### PR DESCRIPTION
**Pull request by mattn**
Added limit of depth 5.

When opening java file on root directory, vim hangs.

### CODE REVIEW

**Comment by artur-shaik** [comment]
Do I understand right that if a:path is direct link on file GlobPathLink return that link?

**Comment by mattn** [comment]
What do you mean `link`? symlink?

**Comment by mattn** [comment]
If yes, then answer is yes. globpath handle symlinks. So:

```
/tmp/aaa/foo
/tmp/bbb/aaa
```

If `/tmp/bbb/aaa` is symlink of `/tmp/aaa`, `globpath("/tmp/bbb", "**/*")` should be `/tmp/bbb/aaa/foo`.

**Comment by artur-shaik** [comment]
No, by link I mean path. So if `a:path` is direct path to jar or zip file, and not a directory.

**Comment by mattn** [comment]
https://github.com/mattn/vim-javacomplete2/commit/5e6422f56be7479c8d35f4bf0b7d4b9d929dee17#diff-60812780f639c2271180fbd367d4d63bR250

Yes, try below on your root of java project directory.
```
:echo globpath(".", "**/*.java")
```

**Comment by artur-shaik** [comment]
Yaeh but if I do:
```
:echo globpath('/home/ash/file.java', '**/*.java')
```
it give me nothing. That what I mean by direct line on file.

**Comment by mattn** [comment]
Ah, okay. will fix.

**Comment by mattn** [comment]
fixed.

**Comment by artur-shaik** [comment]
Yeah, thank you.

**Pull request merged**
