### PR TITLE
[RFC]Add imports sort feature

### PR DESCRIPTION
**Pull request by wsdjeg**
I will try to add sort feature for this plugin, now it is just WIP.
try to implement #207

### CODE REVIEW

**Comment by wsdjeg** [comment]
rebased!

**Comment by wsdjeg** [comment]
I have fixed the extra empty line,when there is no other imports.

**Comment by wsdjeg** [comment]
Fix issue now, after sortting ,it looks like :

**Comment by andrewbenton** [comment]
Looks good to me except that it doesn't seem do any sort of divide by JAR.  I'm not sure if that's possible, but it would be nice to keep them separate.

**Comment by wsdjeg** [comment]
> Looks good to me except that it doesn't seem do any sort of divide by JAR

I am not sure if it is really needed,
as you can see before sort by `g:JavaComplete_ImportOrder`,I have used this func,`call sort(importsList)`,so I think most import from same jar will be together.

**Comment by brcolow** [comment]
You can add the following documentation to README.md if you want (inside the Optional section):

`let g:JavaComplete_ImportOrder = '['java', 'javax', 'com', 'org', 'net']'` - Specifies the order of import groups. An import group is a list of individual import statements that all start with the same top-level package name surrounded by blank lines above and below the group.

For example, setting: `let g:JavaComplete_ImportOrder = '['com', 'org']` and then calling `<Plug>(JavaComplete-Imports-*)` (where *=Add, AddMissing, or RemoveUnused) would yield:

```java
import org.baz.ClassC;
import com.foo.ClassA;
import net.qux.ClassD;
import com.bar.ClassB;
```
```java
import com.foo.ClassB;
import com.bar.ClassB;

import org.bar.ClassA;

import net.baz.ClassC;
```

Hopefully the above information is accurate. Also I wanted to add a detail about subpackages but I was not sure if the current implementation can handle them. What I mean is, is the following supported:

`let g:JavaComplete_ImportOrder = '['com.A', 'com.B']` ?

**Comment by wsdjeg** [comment]
@brcolow 
first,thanks for add something in readme.
and I think it is easy to implement sort by subpackages.but for user,I think `g:JavaComplete_ImportOrder` should be just a list of simple string ,not a list of regular expressions.
let me make some change.

**Comment by wsdjeg** [comment]
hi @brcolow now by default it is `['java.', 'javax.', 'com.', 'org.', 'net.']`,if you want to order bu subpackage name,you can set like this `['java.util.', 'java.sql.', 'com.', 'org.', 'net.']`

**Comment by brcolow** [comment]
@wsdjeg Perfect! Great work.

**Comment by artur-shaik** [comment]
Ok, thanks. I will create separate branch with this modifications. And will investigate more for jar aware sorting.

**Comment by artur-shaik** [comment]
Please add new commits to `import-sorting` branch.

**Comment by wsdjeg** [comment]
can you reopen this PR?and I will push to other branch,just wait this PR be merged.thanks

**Comment by artur-shaik** [comment]
Yeah, ok.

**Comment by wsdjeg** [comment]
maybe we can move all g:var init to autoload/javacomplete.vim,just make sure all of this g:var init after vimenter or after JCStart

**Comment by artur-shaik** [comment]
For me `plugin/javacomplete.vim` looks more like configuration file. And `autoload/javacomplete.vim` already has too much stuff. You think there is a chance for `g:var` not init?

**Comment by wsdjeg** [comment]
plugin/javacomplete.vim will be sourced when the path be added to rtp,enen if it is not java or jsp file.for neobundoe or vundle the rtp changed when call end().if user put let g:var = 'test' after end()
so let g:var =get(......),will get nothing from `g:`.

**Comment by wsdjeg** [comment]
and I will take a look at other plugin,to find out how they init g:var

**Pull request merged**
