### PR TITLE
Fix Gradle errors

### PR DESCRIPTION
**Pull request by DonnieWest**

### CODE REVIEW

**Comment by wsdjeg** [comment]
please check wether gradle has been intalled

**Comment by wsdjeg** [comment]
and if filereadable pom.xml or .classpath,dot not use gradle

**Comment by DonnieWest** [comment]
@wsdjeg that's outside of the scope of this PR. I'm just fixing a typo here, we can discuss other implementation details elsewhere

**Comment by wsdjeg** [comment]
sorry i know thank you

**Pull request merged**
