### PR TITLE
Fix windows support

### PR DESCRIPTION
**Pull request by wsdjeg**
hi @artur-shaik I think we should not use .classpath and pom.xml or build.gradle together,some project has both .classpath and pom.xml

### CODE REVIEW

**Comment by wsdjeg** [comment]
https://github.com/wsdjeg/vim-javacomplete2/commit/33d69adc704c097ba8261ddbb3a8dda25cdd8171
this commit is safe

**Comment by artur-shaik** [comment]
Will check it now...

**Comment by wsdjeg** [comment]
my friends is checking

**Comment by wsdjeg** [comment]
-4a5ce5898b24f21a
mvn success but javac still has issue ,please waitting ,i well fix it

**Comment by wsdjeg** [comment]
must be some thing error with g:FILE_SEP

**Comment by wsdjeg** [comment]
javac and mvn compile both success in win

**Comment by wsdjeg** [comment]
testing competion

**Comment by wsdjeg** [comment]
@artur-shaik I can not fix socket comuniction,now the compile and classpath detection works well both win and linux

**Comment by artur-shaik** [comment]
Ok, thank you. Will check it little bit later.

**Pull request merged**
