### PR TITLE
better pom support

### PR DESCRIPTION
**Pull request by wsdjeg**
help from https://github.com/scrooloose/syntastic/pull/1604/files

### CODE REVIEW

**Comment by wsdjeg** [comment]
please waitting ,let me do more test

**Comment by wsdjeg** [comment]
great it works same as bofore but support pom better,and fix config file end with .xml or .gradle,it can be merge safety

**Comment by wsdjeg** [comment]
second one show the fixed result

**Comment by wsdjeg** [comment]
@mattn where do you comment,i can not see, i will clean up code

**Comment by wsdjeg** [comment]
@mattn can you have a look

**Comment by wsdjeg** [comment]
need to fix

**Comment by mattn** [comment]
Sorry, No need last commit.

**Comment by wsdjeg** [comment]
yes last comment get error

**Comment by mattn** [comment]
Well, I commented in last commit https://github.com/wsdjeg/vim-javacomplete2/commit/10102463a361bc718bd3bf6c48ca19960a6c14dc

But removed comment because it's my fault.

**Comment by wsdjeg** [comment]
why it works well ,but this not
https://github.com/scrooloose/syntastic/commit/10788ac8d78bec29f6662a1b40a75e2b94eaaa31

**Comment by mattn** [comment]
because my suggestion break your changes bits.

**Comment by wsdjeg** [comment]
ok i have reset commit to the right one

**Comment by wsdjeg** [comment]
hi @artur-shaik  @mattn  you are right ,it can be clean up like that ,i will do it ,it my fault

**Comment by wsdjeg** [comment]
hi @mattn i have test it ,it works well ,can you have a try?

**Comment by wsdjeg** [comment]
@artur-shaik  please merge this before it can not be auto merge

**Pull request merged**
