### PR TITLE
fix miss test classes

### PR DESCRIPTION
**Pull request by wsdjeg**
hi @artur-shaik when i complete mvn test class ,some error appeared,so i think it is better add the test class outputdirectory into classpath,what do you think?
https://maven.apache.org/guides/introduction/introduction-to-the-pom.html

### CODE REVIEW

**Comment by artur-shaik** [comment]
What kind of error? Can you put logs here?

**Comment by wsdjeg** [comment]
for example i have i innerclass in `src/test/java/com/wsdjeg/mysqlvim/TestMVRequest.java`
named TestMVRequestInnerclass
can not be complete

after this PR it works ok

**Comment by artur-shaik** [comment]
Ok, lets do it.

**Comment by wsdjeg** [comment]
thank you !

**Comment by wsdjeg** [comment]
i have read syntastic src,it can detect test or main file,and use different properties,i try to let JC2 also support it, but i find it is not a good ieal.bucause JAVAVI servise has started and there is no need to restart when we change to different file!

**Pull request merged**
