### PR TITLE
Fix #246 javacomplete2 source problem

### LINKED ISSUE #246: Issues about deoplete source in javacomplete2.
### 2. can not mannuly complete class name
my insert mode <leader><tab> will call this func
```vim
function! MyLeaderTabfunc() abort
    if g:settings.autocomplete_method == 'deoplete'
        return deoplete#mappings#manual_complete(['omni'])
    elseif g:settings.autocomplete_method == 'neocomplete'
        return neocomplete#start_manual_complete(['omni'])
    endif
endfunction
```
type `\<tab>` after `Sys`
manual source omni works well, also support fuzzy match,but javacomplete2 source can not

### 3 manual source below `@Override`
omni works well, also support fuzzy match
javacomplete2 manual source will show popmenu,but can not fuzzy match

### PR DESCRIPTION
**Pull request by Shougo**
I have fixed #246 problem.
Please test it.

### CODE REVIEW

**Comment by artur-shaik** [comment]
@Shougo , thank you. @wsdjeg can you, please, confirm.

**Comment by wsdjeg** [comment]
@Shougo Thanks,@artur-shaik I will try it tonight.

**Comment by wsdjeg** [comment]
#### 1. fuzzy match works well after dot.
example
```java
    public class Foo{
         public void test(){
                 this._ // cursor here works well.
         }
    }
```
#### 2. complete class name not work, I use manuly source.
 imap `<leaser><tab>` to `deoplete#mappings#manual_complete(['omni','javacomplete2'])`
example
```java
    public class Foo{
         public void test(){
                 Sys_ // cursor here only omni works, also omni support fuzzy match
         }
    }
```

fuzzy match shown here


#### 3. manual complete after `@Ov`, only omni works well,also omni support fuzzy match



#### 4. manual complete below `@Override`, after type into some thing has some error.
I use `call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])`
so I can use `finalize` to match the whole function statement, but only omni works.

**Comment by Shougo** [comment]
Please disable omni source on the example.
Duplicated candidates are hidden by deoplete.

**Comment by Shougo** [comment]
Please use this for the manual completion.

```vim
inoremap <expr><tab> deoplete#mappings#manual_complete(['javacomplete2'])
```

**Comment by wsdjeg** [comment]
@Shougo  I have disable the omni source, but I get the same result,
can not complete class name for example type `<Tab>` after `Stri` should complete all the className begin with `Stri`.

**Comment by Shougo** [comment]
OK.  I will test it.
Please upload the sample Java project.

**Comment by wsdjeg** [comment]
for completion code, there is no difference butween a project and a single java file, so feel free test with this file.
let me show show you some situations.
1. complete after dot.
```java
public class Foo {
     public void test(){
           this._           // _ is the position of cursor, after dot should auto complete,
                            // and should support fuzzy match.  BTW as I test before, this
                            // situation works well.
     }
}
```

2. completion after a string.

```java
public class Foo {
    public static void testm() {
        Str_               // _ is the cursor, here we use manually source javacomplete2
                           // and should complete all the className beging with `Str`, and
                           // fuzzy match should only match the char after `Str`, for example
                           // if I type in to `n`, should match '^Str\w*[nN]\w*'. as I said before
                           // this situation does not work, but omni.py works well.
    }
}
```

3. complete after `@`.

```java
public class Foo {
    @Ov_                  // _ is cursor, here I use manually source javacomplete2 ,and should complete 
                          // the annotation begin with `Ov`, same as complete after a string, should support 
                          // fuzzy match,omni works as expect.
}
```

4. complete below `@Override`

```java
public class Foo {
    @Override
    _                     // here I use manually source, and should complete the method that can be override,
                          // this situation is very different with other situation, because in this case, in the
                          // popupmenu ,each item.word contains `(` and `(` and `{`. for example:
                          // see pic below. the item.word is very long.
}
```

**Comment by Shougo** [comment]
I have reproduced the problem.
I will fix it.

**Comment by Shougo** [comment]
@wsdjeg Please test it again.

**Comment by wsdjeg** [comment]
ok

**Comment by wsdjeg** [comment]
@Shougo I just merge your branch to my master, and tested, but still does not works, just same as before.only after dot works well.

**Comment by Shougo** [comment]
@wsdjeg I have fixed it.  Please test it again.

**Comment by wsdjeg** [comment]
@Shougo thanks, I will test it, but as I can see the changes, not only happened in deoplete source, but also in JC2 core func. I am not sure if it will break origin omni support or break YCM support.

as I can see `function! javacomplete#Complete(findstart, base)` this func do not change, maybe orgin omni and YCM should works well, but I am not sure.

**Comment by Shougo** [comment]
Yes, because the filtering is in javacomplete2 core.
It does not change the YCM and omnifunc behavior.

**Comment by wsdjeg** [comment]
@Shougo I now add an check box here for all the featue omny.py support for javacomplete2.if javacomplete.py support it also, I will add `x`.

- [ ] autocomplete after dot
- [ ] fuzzy match after dot
- [ ] manual complete class name after `Str`
- [ ] fuzzy match after `Str`
- [ ] manual complete class name after `@Ov`
- [ ] fuzzy match after `@Ov`
- [ ] manual complete method below `@Override`
- [ ] fuzzy match below `@Override`

**Comment by Shougo** [comment]
The fuzzy match does not work?
Hm... I cannot reproduce it.
Please describe them.

> BTW, after manually source javacomplete2.py to complete after Str or @Ov or below @Override, the first result should not be inserted, deoplete should only list the result instead of insert the first one. omni.py works well,it will not insert the first result

It seems not javacomplete2.py problem.
I cannot reproduce it.
Please create minimal init.vim and reproduce ways from neovim starting.

**Comment by Shougo** [comment]
> BTW, after manually source javacomplete2.py to complete after Str or @Ov or below @Override, the first result should not be inserted, deoplete should only list the result instead of insert the first one. omni.py works well,it will not insert the first result

It seems deoplete feature.
Please see it.

https://github.com/Shougo/deoplete.nvim/pull/219

**Comment by Shougo** [comment]
I have tested the feature and it works.
I think it is [RDY].
@artur-shaik Ping.

**Comment by wsdjeg** [comment]
@Shougo  I am just creatting an mini vimrc for testting, why I can not fuzzy match in the last 3 situatinon?

**Comment by wsdjeg** [comment]
minivimrc
```vim
" python host for neovim
let g:python_host_prog = '/usr/bin/python2'
let g:python3_host_prog = '/usr/bin/python3'
set runtimepath+=~/forks/deoplete.nvim
set runtimepath+=~/forks/vim-javacomplete2
augroup JC
    au!
    autocmd FileType java setlocal omnifunc=javacomplete#Complete
augroup END
let g:deoplete#enable_at_startup = 1
inoremap <silent> <Leader><Tab> <C-r>=MyLeaderTabfunc()<CR>
function! MyLeaderTabfunc() abort
    return deoplete#mappings#manual_complete(['javacomplete2'])
endfunction
```
test with 
```java
public class Foo{
       public void test(){
             Sys_               // cursor here type `<leader><tab>` in insert mode will open popupmenu, but if I type into any char, the popupmenu will be closed.
       }
}
```

**Comment by wsdjeg** [comment]
I test it with two different config file, one for omni, and one for javacomplete2.py.
**please start neovim by nvim -u test.vim**
### omni
```vim
" python host for neovim
let g:python_host_prog = '/usr/bin/python2'
let g:python3_host_prog = '/usr/bin/python3'
set runtimepath+=~/forks/deoplete.nvim
set runtimepath+=~/forks/vim-javacomplete2
let g:deoplete#enable_refresh_always=1
let g:deoplete#enable_ignore_case = 1
let g:deoplete#enable_smart_case = 1
let g:deoplete#enable_camel_case = 1
let g:deoplete#omni#input_patterns = get(g:,'deoplete#omni#input_patterns',{})
let g:deoplete#omni#input_patterns.java = [
            \'[^. \t0-9]\.\w*',
            \'[^. \t0-9]\->\w*',
            \'[^. \t0-9]\::\w*',
            \]
augroup JC
    au!
    autocmd FileType java setlocal omnifunc=javacomplete#Complete
augroup END
let g:deoplete#enable_at_startup = 1
inoremap <silent> <Leader><Tab> <C-r>=MyLeaderTabfunc()<CR>
function! MyLeaderTabfunc() abort
    return deoplete#mappings#manual_complete(['omni'])
endfunction
call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])
```
test java file 
```java
public class Foo {
    public void test(){
	    
    }
}
```
1. after string

type `<leader><tab>`after`Sys`

then type into `mess`


2. after `@Ov`

type `<leader><tab>`after`@Ov`

then type into `of`

3. below `@Override`

type `<leader><tab>` below `@Override`

type into `clone`

type `<C-n>`

type `<CR>`

**Comment by artur-shaik** [comment]
Seems like I have the same behavior as @wsdjeg describes, when using his miniconf. Some issues when 'javacomplete2' manual complete used.

**Comment by Shougo** [comment]
It is deoplete bug.
I have fixed it.
Please update deoplete and test it.

**Comment by wsdjeg** [comment]
@Shougo I have update deoplete,and finished testing, also I have update that check box.
fuzzy match works well after str and `@Ov`, but below `@Override`
type `<leader><tab>` I get
a
if I type in to `clone` I get 
b
it is ok, but if I type `<C-n>` I only get

instead of 


another issue is the InsertEnter event.
@artur-shaik 's JC2 plugin will auto import class after completion. 
when type `<leader><tab>` after `Str` I get

but if I type `ing`, I get 

I think it is due to deoplete auto close popupmenu before refresh.
in omni after type `ing`
I get

**Comment by wsdjeg** [comment]
please see https://github.com/wsdjeg/vim-javacomplete2/blob/master/autoload/javacomplete.vim#L227-L242

**Comment by wsdjeg** [comment]
and https://github.com/wsdjeg/vim-javacomplete2/blob/master/autoload/javacomplete.vim#L136-L139

**Comment by Shougo** [comment]
> I think it is due to deoplete auto close popupmenu before refresh.
in omni after type ing

Because, the omni seems not real fuzzy match

> another issue is the TextChangedI event.
> @artur-shaik 's JC2 plugin will auto import class after completion. 

It seems the conflict.

**Comment by wsdjeg** [comment]
I am not sure it is a conflict, because I have test other completion for example complete after `Bool` then type `ean`, even if I have `Boolean` class the autoimport will not done. this only happened after `String` this word.


and below `@Override` `<C-n>` just show me the item.abbr instead of item.word

**Comment by Shougo** [comment]
> I am not sure it is a conflict, because I have test other completion for example complete after Bool then type ean, even if I have Boolean class the autoimport will not done. this only happened after String this word.

I think `Boolean` has not auto completion class names.

> and below @Override <C-n> just show me the item.abbr instead of item.word

I don't know the vim-javacomplete2 feature.
javacomplete2 source just gets `c` prefixed candidates.
I think it is not problem.
@artur-shaik Ping.

**Comment by artur-shaik** [comment]
I can confirm. Below the `@Override` with `omni` when press `C-n` we have substitution with full method declaration, like this: `public boolean add(Object object) {`.
With `javacomplete2`, we have only `add`.

**Comment by Shougo** [comment]
I have fixed the problem.
Please test it.

**Comment by wsdjeg** [comment]
Wow, @Shougo it works perfect. all the fuzzy match works well.

But here is the last issue.
after `Str`, I manual source jc2, then if I type into `ing`, the auto import `String` will be called, but I think the autoimport should be call after completion done.

**Comment by artur-shaik** [comment]
@Shougo thank you. @wsdjeg, I think it can be fixed at JC side.

**Comment by wsdjeg** [comment]
nice. thanks Shougo.

**Comment by artur-shaik** [comment]
@wsdjeg, can you, please, try with last commit

**Comment by wsdjeg** [comment]
@artur-shaik autoimport has been fixed, now everything works well, so now there is difference : now auto import will be called after completion done and type an space or `(` ?

**Comment by artur-shaik** [comment]
Yeah, space, dot and (. You can suggest anything.

On 06-12 (05:10), Wang Shidong wrote:
>    [1]@artur-shaik autoimport has been fixed, now everything works well, so
>    now there is difference : now auto import will be called after completion
>    done and type an space or ( ?
> 
>    —
>    You are receiving this because you were mentioned.
>    Reply to this email directly, [2]view it on GitHub, or [3]mute the thread.
> 
>    Reverse link: [4]unknown
> 
> References
> 
>    Visible links
>    1. https://github.com/artur-shaik
>    2. https://github.com/artur-shaik/vim-javacomplete2/pull/247#issuecomment-225429018
>    3. https://github.com/notifications/unsubscribe/AEozu5E7Kp_mhqNE-Ke-jEvHxMveo6cLks5qK_cbgaJpZM4IoGeF
>    4. https://github.com/artur-shaik/vim-javacomplete2/pull/247#issuecomment-225429018

-- 
Best regards,
Artur Shaikhullin

**Comment by wsdjeg** [comment]
I think it is nice feature.

**Comment by Shougo** [comment]
Thanks

**Pull request merged**
