### PR TITLE
Fix EVL108

### PR DESCRIPTION
**Pull request by wsdjeg**
1st argument of fnamemodify should be a valid file-modifier: p

### CODE REVIEW

**Comment by wsdjeg** [comment]
hi @artur-shaik 
There are four EVL105 in `autoload/javacomplete.vim`
```
autoload/javacomplete.vim|261 col 5 warning| [EVL105] global variable `i` is defined without g:
autoload/javacomplete.vim|264 col 5 warning| [EVL105] global variable `src` is defined without g:
autoload/javacomplete.vim|272 col 7 warning| [EVL105] global variable `rjava` is defined without g:
autoload/javacomplete.vim|273 col 7 warning| [EVL105] global variable `r` is defined without g:
```

**Comment by wsdjeg** [comment]
so I can use `echo i` `echo src` `echo rjava` `echo r` any where.it is very danger,I will try to fix it

**Comment by wsdjeg** [comment]
I have added new utils,globpathlist with depth.
```vim
function! javacomplete#util#GlobPathList(path, pattern, suf, depth)
  if has("patch-7.4.279")
    let pathList = globpath(a:path, a:pattern, a:suf, 1)
  else
    let pathList = split(globpath(a:path, a:pattern, a:suf), "\n")
  endif
  if a:depth > 0
    let depths = []
    for i in range(1, a:depth)
      call extend(depths, repeat('*/', i))
    endfor
  endif
  for i in depths
    call extend(pathList, javacomplete#util#GlobPathList(a:path, i. g:FILE_SEP. a:pattern, 0, 0))
  endfor
  return pathList
endfunction
```

**Comment by artur-shaik** [comment]
Thanks. You will do more commits here?

**Comment by wsdjeg** [comment]
yeah,it is WIP

**Comment by wsdjeg** [comment]
```vim
for i in ['*/', '*/*/', '*/*/*/']
  call extend(s:sources, s:GlobPathList(getcwd(), i. g:FILE_SEP. 'src', 0))
endfor
```

Should be changed to 
```vim
for i in ['*/', '*/*/', '*/*/*/']
  call extend(s:sources, s:GlobPathList(getcwd(), i.  'src', 0))
endfor
```

**Comment by wsdjeg** [comment]
In window we need use `"*\"` instead of `'*/'`

**Comment by wsdjeg** [comment]
reabsed

**Comment by wsdjeg** [comment]
any comments?

**Comment by artur-shaik** [comment]
Thanks, looks nice

**Pull request merged**
