### PR TITLE
Fix error on empty scope

### PR DESCRIPTION
**Pull request by mattn**
When start completion at below's location, it occor errors.

### CODE REVIEW

**Comment by wsdjeg** [comment]
can you open a new issue like https://github.com/VundleVim/Vundle.vim/issues/608

**Comment by artur-shaik** [comment]
@mattn you mean on `Test.|` completion call?

**Comment by mattn** [comment]
@artur-shaik leading with `this.`

**Comment by wsdjeg** [comment]
here the plugin now can complete like this.|

**Comment by mattn** [comment]
@artur-shaik I'm not sure this change is best way. so plesae try to fix your self.

**Comment by wsdjeg** [comment]
but if like this wikk miss uncompile file

**Comment by mattn** [comment]
No, this is not uncomplete.

1 complete v
```
this.v;
```
2 add `private String foo =` at before
```
private String foo = this.v;
```
This is strict code.

**Comment by wsdjeg** [comment]
i mean the file which has not been compile!
for example:
Foo.java
```java
public class Foo{
public String a;
}
```
Foo2.java
```java
public class Foo2 extends Foo{
//case one
|
//case two
this.|
}
```

**Comment by mattn** [comment]
Sorry I don't still understand what you mean. Probably it's an another issue. So please file new issue.

**Comment by wsdjeg** [comment]
i have opened thank you all the same

**Pull request merged**
