### PR TITLE
Add <Plug> mappings

### PR DESCRIPTION
**Pull request by mattn**
Add four `<Plug>` mappings to you to customize key mappings like below.

```
imap <c-k>a <Plug>(JavaComplete-Imports-Add)
imap <c-k>r <Plug>(JavaComplete-Imports-RemoveUnused)
```
you can also map on normal mode in same way.
```
nmap <c-k>a <Plug>(JavaComplete-Imports-Add)
nmap <c-k>r <Plug>(JavaComplete-Imports-RemoveUnused)
```

### CODE REVIEW

**Comment by mattn** [comment]
If I say in correctly, you should do mapping to `<plug>` with `<buffer>` like below.
```
imap <buffer> <c-k>a <Plug>(JavaComplete-Imports-Add)
imap <buffer> <c-k>r <Plug>(JavaComplete-Imports-RemoveUnused)
```
:metal:

**Comment by mattn** [comment]
probably AddI should be Add. will fix

**Comment by wsdjeg** [comment]
please do not map keyboard ,using <Plug>(command names )
let people decide which keyboard collection to use themself

**Comment by wsdjeg** [comment]
sorry i have no attention on the file changes

**Comment by mattn** [comment]
Please look the chage carefully. I'm not mapping into keyboard. And please read `:help <Plug>`

**Comment by wsdjeg** [comment]
how fast you reply i have just say no attention

**Comment by artur-shaik** [comment]
Please, can you explain, what advantages it give us?

**Comment by mattn** [comment]
How you define mappings of imports#AddI ? like below?
```
inoremap <leader>ia <esc>:JCimportAddI<cr>
```
For example, `<leader>` should be backslash character if you doesn't modify mapleader.

Then try below. at the first move the cursor into `|`, and type `o\ia`.
```
public class Foo {
	public static void main(String[] args) {|
	}
}
```
Then, cursor should move to top of the line.
```
public class Foo {
	public static void main(String[] args) {
|
	}
}
```
Because typing `<esc>` key reset the indentation in the line. And we must know two interface JCimportsAdd/JCimportsAddI. But user don't have to know which interface is a command to add imports on insert mode. And you will be able to change implementation of the calling of imports#Add if you provide `<Plug>` mapping. For example, adding arguments. Rename function.

**Comment by wsdjeg** [comment]
as i know i have add  two maping 
```vim
inoremap <leader>ia <esc>:JCimportAddI<cr>
nnoremap <leader>ia <esc>:JCimportAdd<cr>
``
if mapping like this is there any bug?

**Comment by wsdjeg** [comment]
i have try with my mapping,the cursor will not change to other please,what is your mapping of this plugin?

**Comment by artur-shaik** [comment]
I see, looks like this is better and cleaner way to call commands in insert mode, right?

**Comment by mattn** [comment]
Combination of `<esc>` and `a` is not perfect for all situations.

**Comment by wsdjeg** [comment]
@mattn  thi pic you show also appear in my pc
if i type F4 in a new line the cursor will change to the beginning of the blank line

**Comment by wsdjeg** [comment]
sorry  it will not appear

**Comment by mattn** [comment]
you need to type `o` before.

**Comment by artur-shaik** [comment]
There is issue for such method. When you in insert mode and have several result for class name, options are not visible. For example for `List` or `Date`.

**Comment by wsdjeg** [comment]
really when i use F4 in new line will change to the beginning  and change to nomal mode

**Comment by mattn** [comment]
Most of advantage is that it's possible to avoid to everyone to know this confusing behavior by this way.

**Comment by artur-shaik** [comment]
@mattn so any thought about issue I have wrote?

**Comment by mattn** [comment]
@artur-shaik fixed.

**Pull request merged**
