### PR TITLE
fix miss src when Definitions g:JavaComplete_SourcesPath

### PR DESCRIPTION
**Pull request by wsdjeg**
i have fix it ,also i have test in my android app

### CODE REVIEW

**Comment by mattn** [comment]
Could you please explain what you do?

**Comment by wsdjeg** [comment]
before i fix it,the plugin judge if the g:JavaComplete_SourcesPath exists?
if not exists let g:JavaComplete_SourcesPath = ' '  auto add all the src into it;

then i fix it by do not clear g:JavaComplete_SourcesPath ,just add src behind it.

**Comment by wsdjeg** [comment]
fix merge Conflict

**Comment by wsdjeg** [comment]
@artur-shaik 
hi i have try with this change,the plugin works very well

**Comment by artur-shaik** [comment]
@wsdjeg I don't know why, but diff show too much changes. Can you edit you changes, so we can see what exactly changed?

**Comment by artur-shaik** [comment]
Ou, I see why, there was indentation changes. Please, fix it.

**Comment by wsdjeg** [comment]
i have fix it ,now the chanage is just ablout autoload/javacomplete.vim
line 237~line 258

**Comment by wsdjeg** [comment]
hi @artur-shaik 
i want to and the branch name to the generate pom.xml's path,so that it will start quick when i change between branch,but now it seemed does not work

**Comment by mattn** [comment]
@wsdjeg well, could you please check your english before posting comment. I'm not native speaker but I'm confusing what you talking about.

**Comment by wsdjeg** [comment]
sorry,i just want and the git branch name to the generated file named ~/.javacomplete2/_path_to_pom.xml

**Comment by mattn** [comment]
@wsdjeg do you mean that you don't like filename of cached pom.xml ? right?

**Comment by wsdjeg** [comment]
just becuse my project on different branch uses different pom.xml,so i need to add the branch name to the geberated pom.xml to let vim start quickly

**Comment by mattn** [comment]
@wsdjeg okay, I understood. But the directory may not be managed with git. So we should consider how to recognize file name of pom.xml

**Comment by wsdjeg** [comment]
yes,i think so.now my PR works well,if has no .git,the branch_name is "",so it will not has problem

**Comment by mattn** [comment]
Could you please make pull-request that fixing one issue. you pull-request contains to fix some issues.

**Comment by wsdjeg** [comment]
hi @mattn  can you have a try on windows

**Comment by wsdjeg** [comment]
it will get error when can not find .git

**Comment by wsdjeg** [comment]
if can not find .git,the generated file will be
`_home_wsdjeg_test_MyFirstApp_pom.xmlfatal: Not a git repository (or any of the parent directories): .git
`

**Pull request closed without merging**
