### PR TITLE
store maven classpath by md5sum in cache file.

### PR DESCRIPTION
**Pull request by richox**

### CODE REVIEW

**Comment by artur-shaik** [comment]
Thank you. I was thinking about hashsum, but we need something for windows users, I guess.
Any ideas?

**Comment by richox** [comment]
bring an md5sum.exe for windows user? or compute checksum inside javavi?

**Comment by mattn** [comment]
how about to use `echo sha256("foo")` on vim script?

**Comment by mattn** [comment]
most user doesn't have md5sum on windows.

**Comment by artur-shaik** [comment]
@mattn, yeah, I decided not to use hashsums.

**Pull request merged**
