### PR TITLE
Adds support for all Gradle classpaths

### PR DESCRIPTION
**Pull request by DonnieWest**
Before this commit, the Gradle classpath was only pulled from the "main"
project. This commit has Gradle run a custom task that outputs all jars
from all projects. It also grabs the exploded aars and android.jar for
the given project and thus adds Android support.

### CODE REVIEW

**Comment by mattn** [comment]
thanks. could you please set `-p` with base directory as same as location that build.gradle is.

**Comment by DonnieWest** [comment]
@mattn not quite sure what you mean, sorry?

**Comment by mattn** [comment]
@DonnieWest I'm thinking this works fine only when the current directory is project root.

**Comment by DonnieWest** [comment]
@mattn In multi module projects the previous behavior ignored the build.gradle in the project root and instead would use the build.gradle of a lower down module.

I'll see if I can somehow combine the two behaviors.

**Comment by DonnieWest** [comment]
@mattn How's that look?

**Comment by mattn** [comment]
Looks good to me.

**Pull request merged**
