### PR TITLE
Fix path to pom.xml

### PR DESCRIPTION
**Pull request by mattn**
When getcwd() is same as pom.xml, `g:JavaComplete_PomPath` become `.`.
Should be absolute path.

### CODE REVIEW

**Comment by mattn** [comment]
plesae wait. this still have problem.

**Comment by mattn** [comment]
please take a look.

**Comment by mattn** [comment]
added `target/classes` into classpath. so this will close #79

**Comment by wsdjeg** [comment]
why need add the classpath , now the plugin works will!

**Comment by mattn** [comment]
when using lombok, there is differentresult between reflection via this plugin and compiled class file.
```java
package io.github.mattn;

import lombok.Data;

@Data
public class Foo {
	private final String message = null;
	public boolean isAlived() {
		return true;
	}
}
```
This should provide method `getMessage`.But javacomplete2 can't detect this `getMessage`.
However, class file in `target/classes` have this.

**Comment by wsdjeg** [comment]
but if you add target/classes into classpath ,will the plugin complete this method? i was using this plugin with vim-root and the pom.xml is located in my pwd! so target/classes already in my classpath

**Comment by wsdjeg** [comment]
the plugin translate my project's pom.xml to ~/.javacomplet2/classpath/pom.xml

**Comment by mattn** [comment]
`~/.javacomplete2/mvnclasspath/pom.xml` may be invalid. it should be like `_path_to_your_root_directory_pom.xml`. and `mvn dependency:build-classpath -DincludeScope=test` doesn't contains `target/classes`.

**Comment by artur-shaik** [comment]
@wsdjeg have you cleaned `~/.javacomplete/mvnclasspath` before

**Comment by wsdjeg** [comment]
now i will delete my ~/.javacomplete/mvnclasspath,

**Comment by wsdjeg** [comment]
great ! when did you add this func ,i think i could close all my issue thank you for you work

**Comment by artur-shaik** [comment]
@mattn thanks.

**Comment by mattn** [comment]
:metal:

**Comment by wsdjeg** [comment]
I wonder,why can not add friends in github,the only way is following?

**Pull request merged**
