### PR TITLE
Hiding the server window on Windows

### PR DESCRIPTION
**Pull request by adelarsq**
Hiding the server window on MS Windows.

### CODE REVIEW

**Comment by wsdjeg** [comment]
it can not work. when :e Foo.java get this error

**Comment by adelarsq** [comment]
Can you try again?

**Comment by wsdjeg** [comment]
what is your os?i am not near my pc,will try it tonight

**Comment by adelarsq** [comment]
Was on Windows 7. With the first version did work fine, same for the new change. I don't know if will work for you.

**Comment by wsdjeg** [comment]
> With the first version did work fine

when you open a new java file ,there is no extra black windows? if so no need to change anything, i am using xp just for testing,also the xp os is discarded.
*  can you complete import statement now?
* maybe I need to install win7 in the vbox

**Comment by adelarsq** [comment]
No, it's just the change to hide the window that work. Imports are still broken.

Imports from the same project are working. Imports from another projects don't (maven dependences and default packages like java.util.*). It worked some time ago, so there are something broke for MS Windows.

**Pull request merged**
