### PR TITLE
Be a nice plugin and ignore vim help tags

### PR DESCRIPTION
**Pull request by Tharre**

### CODE REVIEW

**Comment by artur-shaik** [comment]
@perrin4869 , can you participate, I have already forget why we periodically add and remove this tags :smile:

**Comment by wsdjeg** [comment]
see https://github.com/artur-shaik/vim-javacomplete2/commit/7aaba874bea8fefbe6fcddcc4eeb6775a6e12724
and 
https://github.com/artur-shaik/vim-javacomplete2/commit/c3813ce52b44e7dae02159013430cba4bd1a8b47

**Comment by wsdjeg** [comment]
and here: https://github.com/artur-shaik/vim-javacomplete2/pull/237

**Comment by artur-shaik** [comment]
So, @Tharre, what are your arguments on #237?

**Comment by Tharre** [comment]
I don't quite understand why they were removed in #247. The author states that "conceptually speaking it doesn't make sense to ignore them", but doesn't say why he thinks it makes no sense.

Generally speaking, all files that may be created in a git repo during normal operation and that should not be committed should be added to .gitignore, to ensure they remain untracked.
From the git docs:

    The purpose of gitignore files is to ensure that certain files not tracked by Git remain untracked.

Furthermore, by having dirty files in your repo, you're messing up the dotfiles of everyone who's using git submodules. Note that they can't simply put `tags` into their .gitignore either, because submodules only honor their own .gitignore files.

**Comment by perrin4869** [comment]
@Tharre I think the reason I wanted to remove them was, that users may choose not to generate the tag files, and then the line in `.gitignore` would be superfluous since `.tags` wouldn't even exist. If a user choose to generate these tags, he could ignore it on his own with his global `.gitignore`

**Comment by Tharre** [comment]
@perrin4869 who cares if there is an additional line in .gitignore that *some* people don't need? The fact that there are users who do need said line should be enough justification to have it in there.

Your workaround doesn't work with submodules, as I've stated above.

**Comment by artur-shaik** [comment]
While I didn't have any issues with this files, I think I share the view of @Tharre. And going to merge it.

Thanks.

**Pull request merged**
