### PR TITLE
autocompletewithoutYCMorNeocomplet

### PR DESCRIPTION
**Pull request by wsdjeg**
I think this function could be add into this plugin,as you know many peopel does not use YCM or other autocomplete plugin,so i add this function in it ,add this will not slowdown the speed of complete!
if any one want to use this function, he just need to add this to his vimrc
```vim
let g:auto_javacomplete2_wsd = 1
```
if do not add this to vimrc ,it just same as the previous commit!

### CODE REVIEW

**Comment by wsdjeg** [comment]
https://github.com/artur-shaik/vim-javacomplete2/issues/73

**Comment by Shougo** [comment]
I think you should not use the mapping feature to implement auto completion feature.
It is easy to conflict with other plugins or user configuration.

**Comment by DonnieWest** [comment]
@Shougo agreed. If the user wants this behavior they can add it to their own vimrc. This is also out of the scope of JavaComplete

**Comment by Shougo** [comment]
I think the filetype plugin like clang_complete or vim-javacomplete2 should not provide the auto completion feature.
It should be provided auto completion engine plugins like autocomplpop, neocomplete, YCM.

**Comment by wsdjeg** [comment]
yes maybe i should close this PR

**Pull request closed without merging**
