### PR TITLE
Make Javacomplete works with python 2 or 3.

### PR DESCRIPTION
**Pull request by Townk**
[Problem]
Currently javacomplete plugin relies on Python to do some of its work.
Unfortunately it strictly rely on Python 2 even though the code can run on
Python 3 without any problem.

[Solution]
Make the code first check which Python is available and the first one.

[Notes]
This change essentially remove the use of pyeval due the fact Vim does not
support this function if only Python 3 is available.

Also, I put a check on the beginning of the file to guarantee that we don't
proceed if no Pythno is available.

Signed-off-by: Thiago Alves <talk@thiagoalves.com.br>

### CODE REVIEW

**Comment by artur-shaik** [comment]
Thanks, will check it. 
But before, can you make changes that apply only to your modification. Without ident changes. And let version be 2.2 until the release.

**Comment by Townk** [comment]
Sure, no problem. After I create the pull request I realized I forgot to turn off the remove of white spaces after save on my vimrc. Will create a new one in a bit.

**Comment by mattn** [comment]
@Townk well, your patch still contains changes that not related on this issue.

https://patch-diff.githubusercontent.com/raw/artur-shaik/vim-javacomplete2/pull/33.patch

you have better to separate patch
* remove needless whitespaces
* support python 2 or 3 both

**Comment by mattn** [comment]
And I noticed you define `Pyfile` command in global scope. buffer-local is better. if it doesn't work, you should define them if it not defined.

**Comment by Townk** [comment]
@mattn if I define the commands as buffer commands wouldn't that cause problems to the second java file I open?

Also, I already rolled back the white space changes.

**Comment by mattn** [comment]
See https://patch-diff.githubusercontent.com/raw/artur-shaik/vim-javacomplete2/pull/33.patch

If merge this PR, this patch will be merged.

**Comment by mattn** [comment]
> if I define the commands as buffer commands wouldn't that cause problems to the second java file I open?

I'm not sure. But at least you need to block like below.

```vim
if !exists(':PyFile')
  " define PyFile
endif

**Comment by mattn** [comment]
Your patch should be like below.

https://gist.github.com/mattn/abfa8bbe7ed0194f62a7

Sorry, I don't apply this patch yet.

**Comment by Townk** [comment]
Got it. Two things:

1. Do you guys see my second revision of this patch? I mean, the one where I remove the changes not related to the fix including the version bump Arthur asked me to not change? If I click on the "Files changed" tab here I can see it, can you guys do it as well?

2. The reason why I didn't verify if the command existed was the "command!" portion of it. If the command existed I would override it. I know this is a bed choice and I agree with you that checking is the right approach but my line of though was that I can't guarantee the command created by other plugin or even the user actually represent what I'm trying to create. Maybe I should have appended the plugin name like "Javacomplete_Py" and "Javacomplete_Pyfile", this way it would be very clear whom is the owner of this command.

**Comment by artur-shaik** [comment]
1. I already merge it, there were nothing unnecessary.

2. Yeah, I think `Javacomplete` prefix gives more guarantees that nothing will be broken.

**Comment by Townk** [comment]
Thanks Arthur, I'll do the changes on the command prefix. I'll push a PR by EOD.

**Pull request merged**
