### PR TITLE
win support fix #165,fix #154

### LINKED ISSUE #154: No javavi library classes found, it means that we couldn't compile it. Do you have JDK7+ installed?
This appear in my Windows 7 with JDK8. I didn't install my JDK in the default path, but another place.
This is my jdk configure:

JAVA_HOME = C:\bin\Java\jdk1.8.0_66
CLASSPATH = .;%JAVA_HOME%\lib\dt.jar;%JAVA_HOME%\lib\tools.jar;
PATH = C:\ProgramData\Oracle\Java\javapath;%JAVA_HOME%\bin;%JAVA_HOME%\jre\bin;C:\bin\Vim74\vim74\;

Please help me a little.

### LINKED ISSUE #165: No Javavi library classes found
I'm using GVim (version info below) with JDK 8 (version information below). I'm receiving the following message as soon as I write to any *.java file: ```No javavi library classes found, it means that we couldn't compile it. Do you have JDK8+ installed?```

I see in the documentation for vim-javacomplete2 that it is required to have write access to the place where the javavi library will be compiled. I'm fairly sure I have this, but I'm also not sure where this location would be, exactly. Can I get some help getting this plugin to work on my system?

Path to JDK:  ```C:\Program Files\Java\jdk1.8.0_65```
Path to JRE: ```C:\Program Files\Java\jre1.8.0_66```

Output of ```java -version```: 
```
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b18, mixed mode)
```

Vim version info
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 22 2015 21:36:18)
MS-Windows 32-bit GUI version
Included patches: 1-979
Compiled by jrinehar@JRINEHAR
Huge version with GUI.  Features included (+) or not (-):
+acl                +digraphs           +libcall            +profile            +textobjects
+arabic             -directx            +linebreak          +python/dyn         +title
+autocmd            -dnd                +lispindent         -python3            +toolbar
+balloon_eval       -ebcdic             +listcmds           +quickfix           +user_commands
+browse             +emacs_tags         +localmap           +reltime            +vertsplit
++builtin_terms     +eval               +lua/dyn            +rightleft          +virtualedit
+byte_offset        +ex_extra           +menu               -ruby               +visual
+cindent            +extra_search       +mksession          +scrollbind         +visualextra
+clientserver       +farsi              +modify_fname       +signs              +viminfo
+clipboard          +file_in_path       +mouse              +smartindent        +vreplace
+cmdline_compl      +find_in_path       +mouseshape         -sniff              +wildignore
+cmdline_hist       +float              +multi_byte_ime/dyn +startuptime        +wildmenu
+cmdline_info       +folding            +multi_lang         +statusline         +windows
+comments           -footer             -mzscheme           -sun_workshop       +writebackup
+conceal            +gettext/dyn        +netbeans_intg      +syntax             -xfontset
+cryptv             -hangul_input       -ole                +tag_binary         -xim
+cscope             +iconv/dyn          +path_extra         +tag_old_static     -xterm_save
+cursorbind         +insert_expand      -perl               -tag_any_white      +xpm_w32
+cursorshape        +jumplist           +persistent_undo    -tcl                
+dialog_con_gui     +keymap             -postscript         -tgetent            
+diff               +langmap            +printer            -termresponse       
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: gcc -Iproto -DWIN32 -DWINVER=0x0500 -D_WIN32_WINNT=0x0500 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_GUI_W32 -DFEAT_CLIPBOARD -DFEAT_MBYTE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -w -march=i386 -Wall -Ic:/lua/include -Ic:/lua -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL="lua53.dll" -DFEAT_PYTHON  -DDYNAMIC_PYTHON -DFEAT_XPM_W32 -I xpm/x86/include -I xpm/x86/../include -O3 -fomit-frame-pointer -freg-struct-return -s
Linking: gcc -Iproto -DWIN32 -DWINVER=0x0500 -D_WIN32_WINNT=0x0500 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_GUI_W32 -DFEAT_CLIPBOARD -DFEAT_MBYTE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -pipe -w -march=i386 -Wall -Ic:/lua/include -Ic:/lua -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL="lua53.dll" -DFEAT_PYTHON  -DDYNAMIC_PYTHON -DFEAT_XPM_W32 -I xpm/x86/include -I xpm/x86/../include -O3 -fomit-frame-pointer -freg-struct-return -s -mwindows -o gvim.exe -lkernel32 -luser32 -lgdi32 -ladvapi32 -lcomdlg32 -lcomctl32 -lversion -lwsock32 -Lxpm/x86/lib -lXpm -lole32 -luuid```

### PR DESCRIPTION
**Pull request by wsdjeg**

### CODE REVIEW

**Comment by wsdjeg** [comment]
@artur-shaik @fuzzybear3965 @zhaochenyou 
i have fixed win support ,only need install jdk 1.8,no need maven, can you check this pr?

**Comment by artur-shaik** [comment]
Nice, thanks.

**Comment by wsdjeg** [comment]
got it ,the server start command also has some issue

**Comment by artur-shaik** [comment]
Looks like `-base` argument value should be wrapped, too. The same for `-project`

**Comment by wsdjeg** [comment]
i am use echom classpath .':'.args in server start function ,

**Comment by wsdjeg** [comment]
the import still does not work.

**Comment by wsdjeg** [comment]
ok,i will try to clean up ,and fix the import issue in windows tonight

**Comment by fuzzybear3965** [comment]
Hey, you guys, sorry to be late to the game. I've used Vundle to uninstall the plugin, I've removed Maven from the Windows %PATH% and I have re-installed the plugin using Vundle. The installation is still not working automatically. It fails with the following error:
```
C:\Windows\system32\cmd.exe /c (javac -d ^"C:\Users\John Rinehart\vimfiles\bundl
e\vim-javacomplete2\libs\javavi\target\classes^" -classpath ^"C:\Users\John Rine
hart\vimfiles\bundle\vim-javacomplete2\libs\javavi\target\classes;C:\Users\John
Rinehart\vimfiles\bundle\vim-javacomplete2\libs\javaparser.jar^" -sourcepath ^"C
:\Users\John Rinehart\vimfiles\bundle\vim-javacomplete2\libs\javavi\src\main\jav
a^" -g -nowarn -target 1.8 -source 1.8 -encoding UTF-8 ^"C:\Users\John Rinehart\
vimfiles\bundle\vim-javacomplete2\libs\javavi\src\main\java\kg\ash\javavi\Javavi
.java^")
Note: C:\Users\John Rinehart\vimfiles\bundle\vim-javacomplete2\libs\javavi\src\m
ain\java\kg\ash\javavi\cache\Cache.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Comment by wsdjeg** [comment]
it is not error,please check is target empty!

**Comment by fuzzybear3965** [comment]
Nah, you're right. The ```target``` directory has a ```classes``` subdirectory. There is a whole bunch of stuff under the ```classes``` directory.

**Comment by wsdjeg** [comment]
```
C:\Windows\system32\cmd.exe /c (javac -d ^"C:\Users\John Rinehart\vimfiles\bundl
e\vim-javacomplete2\libs\javavi\target\classes^" -classpath ^"C:\Users\John Rine
hart\vimfiles\bundle\vim-javacomplete2\libs\javavi\target\classes;C:\Users\John
Rinehart\vimfiles\bundle\vim-javacomplete2\libs\javaparser.jar^" -sourcepath ^"C
:\Users\John Rinehart\vimfiles\bundle\vim-javacomplete2\libs\javavi\src\main\jav
a^" -g -nowarn -target 1.8 -source 1.8 -encoding UTF-8 ^"C:\Users\John Rinehart\
vimfiles\bundle\vim-javacomplete2\libs\javavi\src\main\java\kg\ash\javavi\Javavi
.java^")
Note: C:\Users\John Rinehart\vimfiles\bundle\vim-javacomplete2\libs\javavi\src\m
ain\java\kg\ash\javavi\cache\Cache.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```
this message just show you the command which has been exec,by the way,if user do not want to see this,we can provide a g:var to set whether hidde it in next version

**Comment by fuzzybear3965** [comment]
Nah, I didn't construe that message as an error. It was the prompt to use ```Xlint``` that made me think that there was an error. It's good to see the command output. It lets me identify what's happening.

**Comment by wsdjeg** [comment]
> It lets me identify what's happening.

that why we does not hidden it

**Pull request merged**
